# Generated by Django 2.2.1 on 2019-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurb',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
    ]
