# Generated by Django 2.2.1 on 2019-05-14 08:17

from django.db import migrations
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0002_post_blurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resources_needed',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
