# Generated by Django 2.2.1 on 2019-05-15 02:27

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190514_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=wagtail.core.fields.RichTextField(verbose_name='Content'),
        ),
    ]
