# Generated by Django 2.2.1 on 2019-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190515_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=models.TextField(blank=True, max_length=320, null=True),
        ),
    ]
